name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./Application-Code/backend
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/backend
        run: |
          docker build -t $DOCKERHUB_REPO:${{ github.run_number }} .
          docker push $DOCKERHUB_REPO:${{ github.run_number }}

      - name: Update Kubernetes deployment file
        working-directory: ./manifest-files/Backend
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/backend
        run: |
          git config user.email "sandeepreddymunagala@gmail.com"
          git config user.name "munagalasandeep99"
          sed -i "s|$DOCKERHUB_REPO:[0-9]*|$DOCKERHUB_REPO:${{ github.run_number }}|" deployment.yaml
          git add deployment.yaml
          git commit -m "Update backend deployment image to version ${{ github.run_number }} [skip ci]"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
