apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      # Specifies the secret to use for pulling images from private registries like ECR
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        # Updated image to pull from your ECR repository
        image: 116321083906.dkr.ecr.us-east-1.amazonaws.com/frontend:15
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-config # Name of the ConfigMap
                key: REACT_APP_BACKEND_URL # Key within the ConfigMap
        ports:
        - containerPort: 3000
