datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://<prometheus server loadBalancer address>
      access: proxy
      isDefault: true